# Generated by Django 5.2.8 on 2025-12-01 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_pregnant_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='MemberPregnancy',
            fields=[
                ('member', models.OneToOneField(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pregnancy', serialize=False, to='members.member')),
                ('birth_year', models.IntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('due_date', models.DateField()),
                ('preg_week', models.IntegerField()),
                ('gestational_diabetes', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MEMBER_PREGNANCY',
            },
        ),
    ]
