# Generated by Django 5.2.8 on 2025-12-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('is_pregnant_mode', models.CharField(default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_pressure_high', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_low', models.IntegerField(blank=True, null=True)),
                ('blood_sugar', models.FloatField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='members.member')),
            ],
            options={
                'db_table': 'HEALTH_RECORD',
            },
        ),
    ]
