# Generated by Django 5.2.8 on 2025-12-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpregnancy',
            name='id',
        ),
        migrations.AlterField(
            model_name='memberpregnancy',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pregnancy', serialize=False, to='members.member'),
        ),
    ]
