# Generated by Django 5.2.8 on 2025-12-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_memberpregnancy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_column='member_id', help_text='임산부의 Firebase UID (MEMBER.id 참조)', max_length=128)),
                ('guardian_member_id', models.CharField(db_column='guardian_member_id', help_text='보호자의 Firebase UID (MEMBER.id 참조)', max_length=128)),
                ('relation_type', models.CharField(db_column='relation_type', help_text='관계 타입 (배우자, 부모님, 가족, 형제자매, 지인 등)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'FAMILY_RELATION',
                'managed': True,
                'indexes': [models.Index(fields=['member_id'], name='FAMILY_RELA_member__70b7cc_idx'), models.Index(fields=['guardian_member_id'], name='FAMILY_RELA_guardia_1b6557_idx')],
                'unique_together': {('member_id', 'guardian_member_id')},
            },
        ),
    ]
