"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

SECRET_KEY = 'django-insecure-t=p59=vn4z@m3_e@ds)!0*-sc3e&uy%j=k57r&p#-f)8=48vf%'

DEBUG = True

# 공용 DB 사용 시: 다른 사람들이 서버에 접속할 수 있도록 허용
# 개발 환경에서는 모든 호스트 허용 (프로덕션에서는 특정 IP만 허용)
ALLOWED_HOSTS = ['*']  # 개발용: 모든 호스트 허용
# 프로덕션에서는: ALLOWED_HOSTS = ['192.168.0.100', 'your-domain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'members',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ✅ DB 설정
# PostgreSQL 사용하려면 아래 USE_POSTGRESQL을 True로 변경하고 비밀번호를 입력하세요
USE_POSTGRESQL = True  # True로 변경하면 PostgreSQL 사용

if USE_POSTGRESQL:
    # PostgreSQL 사용 (공용 DB)
    # 아래 값들을 pgAdmin에서 설정한 값으로 수정하세요
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'dx_ontime_db',        # 데이터베이스 이름
            'USER': 'dx_user',             # 사용자 이름
            'PASSWORD': 'mypass1234',                # ⚠️ 여기에 pgAdmin에서 설정한 비밀번호 입력
            'HOST': 'localhost',           # localhost 또는 서버 IP 주소
            'PORT': '5432',                # PostgreSQL 포트
        }
    }
else:
    # SQLite 사용 (로컬 개발용 - 기본값)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# (필요하면 나중에 CORS 설정도 추가 가능)
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_ALL_ORIGINS = True
