// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-DWJ-hWf9lCfAzEQ0uqQIRnOH1P4HUM4',
    appId: '1:946831801404:web:6f1f89421e1192f1f85739',
    messagingSenderId: '946831801404',
    projectId: 'pregnantapp-492e6',
    authDomain: 'pregnantapp-492e6.firebaseapp.com',
    storageBucket: 'pregnantapp-492e6.firebasestorage.app',
    measurementId: 'G-9XV7LSFY5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnvyMiXUXdaWb4nYtY621XWYg-saqvTs',
    appId: '1:946831801404:android:3e6865d84dc3e406f85739',
    messagingSenderId: '946831801404',
    projectId: 'pregnantapp-492e6',
    storageBucket: 'pregnantapp-492e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fDDFMM_ducnN9u5hGz64HvuIeA79LEo',
    appId: '1:946831801404:ios:13781814623f3472f85739',
    messagingSenderId: '946831801404',
    projectId: 'pregnantapp-492e6',
    storageBucket: 'pregnantapp-492e6.firebasestorage.app',
    iosBundleId: 'com.example.dxProjectPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6fDDFMM_ducnN9u5hGz64HvuIeA79LEo',
    appId: '1:946831801404:ios:13781814623f3472f85739',
    messagingSenderId: '946831801404',
    projectId: 'pregnantapp-492e6',
    storageBucket: 'pregnantapp-492e6.firebasestorage.app',
    iosBundleId: 'com.example.dxProjectPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-DWJ-hWf9lCfAzEQ0uqQIRnOH1P4HUM4',
    appId: '1:946831801404:web:dd537016c2aa7dbdf85739',
    messagingSenderId: '946831801404',
    projectId: 'pregnantapp-492e6',
    authDomain: 'pregnantapp-492e6.firebaseapp.com',
    storageBucket: 'pregnantapp-492e6.firebasestorage.app',
    measurementId: 'G-KW541V7GZR',
  );
}
